[project]
name = "iksolver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ikpy>=3.4.2",
    "matplotlib>=3.10.3",
]
